/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.rismch.verovio;

public class toolkit {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected toolkit(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(toolkit obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        verovioJNI.delete_toolkit(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public toolkit(boolean initFont) {
    this(verovioJNI.new_toolkit__SWIG_0(initFont), true);
  }

  public toolkit() {
    this(verovioJNI.new_toolkit__SWIG_1(), true);
  }

  public String getUuid() {
    return verovioJNI.toolkit_getUuid(swigCPtr, this);
  }

  public SWIGTYPE_p_Options getOptions() {
    long cPtr = verovioJNI.toolkit_getOptions__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Options(cPtr, false);
  }

  public boolean setResourcePath(String path) {
    return verovioJNI.toolkit_setResourcePath(swigCPtr, this, path);
  }

  public boolean loadFile(String filename) {
    return verovioJNI.toolkit_loadFile(swigCPtr, this, filename);
  }

  public boolean loadData(String data) {
    return verovioJNI.toolkit_loadData(swigCPtr, this, data);
  }

  public boolean saveFile(String filename) {
    return verovioJNI.toolkit_saveFile(swigCPtr, this, filename);
  }

  public String getOptions(boolean defaultValues) {
    return verovioJNI.toolkit_getOptions__SWIG_1(swigCPtr, this, defaultValues);
  }

  public String getAvailableOptions() {
    return verovioJNI.toolkit_getAvailableOptions(swigCPtr, this);
  }

  public boolean setOptions(String json_options) {
    return verovioJNI.toolkit_setOptions(swigCPtr, this, json_options);
  }

  public String getOption(String option, boolean defaultValue) {
    return verovioJNI.toolkit_getOption__SWIG_0(swigCPtr, this, option, defaultValue);
  }

  public String getOption(String option) {
    return verovioJNI.toolkit_getOption__SWIG_1(swigCPtr, this, option);
  }

  public boolean setOption(String option, String value) {
    return verovioJNI.toolkit_setOption(swigCPtr, this, option, value);
  }

  public boolean edit(String json_editorAction) {
    return verovioJNI.toolkit_edit(swigCPtr, this, json_editorAction);
  }

  public String getLog() {
    return verovioJNI.toolkit_getLog(swigCPtr, this);
  }

  public String getVersion() {
    return verovioJNI.toolkit_getVersion(swigCPtr, this);
  }

  public boolean renderToDeviceContext(int pageNo, SWIGTYPE_p_DeviceContext deviceContext) {
    return verovioJNI.toolkit_renderToDeviceContext(swigCPtr, this, pageNo, SWIGTYPE_p_DeviceContext.getCPtr(deviceContext));
  }

  public String renderToSVG(int pageNo, boolean xml_declaration) {
    return verovioJNI.toolkit_renderToSVG__SWIG_0(swigCPtr, this, pageNo, xml_declaration);
  }

  public String renderToSVG(int pageNo) {
    return verovioJNI.toolkit_renderToSVG__SWIG_1(swigCPtr, this, pageNo);
  }

  public String renderToSVG() {
    return verovioJNI.toolkit_renderToSVG__SWIG_2(swigCPtr, this);
  }

  public boolean renderToSVGFile(String filename, int pageNo) {
    return verovioJNI.toolkit_renderToSVGFile__SWIG_0(swigCPtr, this, filename, pageNo);
  }

  public boolean renderToSVGFile(String filename) {
    return verovioJNI.toolkit_renderToSVGFile__SWIG_1(swigCPtr, this, filename);
  }

  public boolean renderToMIDIFile(String filename) {
    return verovioJNI.toolkit_renderToMIDIFile(swigCPtr, this, filename);
  }

  public String renderToMIDI() {
    return verovioJNI.toolkit_renderToMIDI(swigCPtr, this);
  }

  public String renderToTimemap() {
    return verovioJNI.toolkit_renderToTimemap(swigCPtr, this);
  }

  public boolean renderToTimemapFile(String filename) {
    return verovioJNI.toolkit_renderToTimemapFile(swigCPtr, this, filename);
  }

  public String getHumdrumBuffer() {
    return verovioJNI.toolkit_getHumdrumBuffer(swigCPtr, this);
  }

  public void setHumdrumBuffer(String contents) {
    verovioJNI.toolkit_setHumdrumBuffer(swigCPtr, this, contents);
  }

  public boolean getHumdrumFile(String filename) {
    return verovioJNI.toolkit_getHumdrumFile(swigCPtr, this, filename);
  }

  public void getHumdrum(SWIGTYPE_p_std__ostream output) {
    verovioJNI.toolkit_getHumdrum__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(output));
  }

  public String getHumdrum() {
    return verovioJNI.toolkit_getHumdrum__SWIG_1(swigCPtr, this);
  }

  public String getElementsAtTime(int millisec) {
    return verovioJNI.toolkit_getElementsAtTime(swigCPtr, this, millisec);
  }

  public String getMEI(int pageNo, boolean scoreBased) {
    return verovioJNI.toolkit_getMEI__SWIG_0(swigCPtr, this, pageNo, scoreBased);
  }

  public String getMEI(int pageNo) {
    return verovioJNI.toolkit_getMEI__SWIG_1(swigCPtr, this, pageNo);
  }

  public String getMEI() {
    return verovioJNI.toolkit_getMEI__SWIG_2(swigCPtr, this);
  }

  public String getElementAttr(String xmlId) {
    return verovioJNI.toolkit_getElementAttr(swigCPtr, this, xmlId);
  }

  public void redoLayout() {
    verovioJNI.toolkit_redoLayout(swigCPtr, this);
  }

  public void redoPagePitchPosLayout() {
    verovioJNI.toolkit_redoPagePitchPosLayout(swigCPtr, this);
  }

  public int getPageWithElement(String xmlId) {
    return verovioJNI.toolkit_getPageWithElement(swigCPtr, this, xmlId);
  }

  public int getTimeForElement(String xmlId) {
    return verovioJNI.toolkit_getTimeForElement(swigCPtr, this, xmlId);
  }

  public boolean setScale(int scale) {
    return verovioJNI.toolkit_setScale(swigCPtr, this, scale);
  }

  public int getScale() {
    return verovioJNI.toolkit_getScale(swigCPtr, this);
  }

  public boolean setFormat(String informat) {
    return verovioJNI.toolkit_setFormat__SWIG_0(swigCPtr, this, informat);
  }

  public void setFormat(fileFormat format) {
    verovioJNI.toolkit_setFormat__SWIG_1(swigCPtr, this, format.swigValue());
  }

  public int getFormat() {
    return verovioJNI.toolkit_getFormat(swigCPtr, this);
  }

  public boolean setOutputFormat(String outformat) {
    return verovioJNI.toolkit_setOutputFormat__SWIG_0(swigCPtr, this, outformat);
  }

  public void setOutputFormat(fileFormat format) {
    verovioJNI.toolkit_setOutputFormat__SWIG_1(swigCPtr, this, format.swigValue());
  }

  public int getOutputFormat() {
    return verovioJNI.toolkit_getOutputFormat(swigCPtr, this);
  }

  public fileFormat identifyInputFormat(String data) {
    return fileFormat.swigToEnum(verovioJNI.toolkit_identifyInputFormat(swigCPtr, this, data));
  }

  public void setScoreBasedMei(boolean scoreBasedMei) {
    verovioJNI.toolkit_setScoreBasedMei(swigCPtr, this, scoreBasedMei);
  }

  public boolean getScoreBasedMei() {
    return verovioJNI.toolkit_getScoreBasedMei(swigCPtr, this);
  }

  public int getPageCount() {
    return verovioJNI.toolkit_getPageCount(swigCPtr, this);
  }

  public boolean drag(String elementId, int x, int y) {
    return verovioJNI.toolkit_drag(swigCPtr, this, elementId, x, y);
  }

  public boolean insert(String elementType, String startId, String endId) {
    return verovioJNI.toolkit_insert(swigCPtr, this, elementType, startId, endId);
  }

  public boolean set(String elementId, String attrType, String attrValue) {
    return verovioJNI.toolkit_set(swigCPtr, this, elementId, attrType, attrValue);
  }

}
