/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.rismch.verovio;

public class verovioJNI {
  public final static native int UNKNOWN_get();
  public final static native long new_toolkit__SWIG_0(boolean jarg1);
  public final static native long new_toolkit__SWIG_1();
  public final static native void delete_toolkit(long jarg1);
  public final static native String toolkit_getUuid(long jarg1, toolkit jarg1_);
  public final static native long toolkit_getOptions__SWIG_0(long jarg1, toolkit jarg1_);
  public final static native boolean toolkit_setResourcePath(long jarg1, toolkit jarg1_, String jarg2);
  public final static native boolean toolkit_loadFile(long jarg1, toolkit jarg1_, String jarg2);
  public final static native boolean toolkit_loadData(long jarg1, toolkit jarg1_, String jarg2);
  public final static native boolean toolkit_saveFile(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_getOptions__SWIG_1(long jarg1, toolkit jarg1_, boolean jarg2);
  public final static native String toolkit_getAvailableOptions(long jarg1, toolkit jarg1_);
  public final static native boolean toolkit_setOptions(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_getOption__SWIG_0(long jarg1, toolkit jarg1_, String jarg2, boolean jarg3);
  public final static native String toolkit_getOption__SWIG_1(long jarg1, toolkit jarg1_, String jarg2);
  public final static native boolean toolkit_setOption(long jarg1, toolkit jarg1_, String jarg2, String jarg3);
  public final static native boolean toolkit_edit(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_getLog(long jarg1, toolkit jarg1_);
  public final static native String toolkit_getVersion(long jarg1, toolkit jarg1_);
  public final static native boolean toolkit_renderToDeviceContext(long jarg1, toolkit jarg1_, int jarg2, long jarg3);
  public final static native String toolkit_renderToSVG__SWIG_0(long jarg1, toolkit jarg1_, int jarg2, boolean jarg3);
  public final static native String toolkit_renderToSVG__SWIG_1(long jarg1, toolkit jarg1_, int jarg2);
  public final static native String toolkit_renderToSVG__SWIG_2(long jarg1, toolkit jarg1_);
  public final static native boolean toolkit_renderToSVGFile__SWIG_0(long jarg1, toolkit jarg1_, String jarg2, int jarg3);
  public final static native boolean toolkit_renderToSVGFile__SWIG_1(long jarg1, toolkit jarg1_, String jarg2);
  public final static native boolean toolkit_renderToMIDIFile(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_renderToMIDI(long jarg1, toolkit jarg1_);
  public final static native String toolkit_renderToTimemap(long jarg1, toolkit jarg1_);
  public final static native boolean toolkit_renderToTimemapFile(long jarg1, toolkit jarg1_, String jarg2);
  public final static native String toolkit_getHumdrumBuffer(long jarg1, toolkit jarg1_);
  public final static native void toolkit_setHumdrumBuffer(long jarg1, toolkit jarg1_, String jarg2);
  public final static native boolean toolkit_getHumdrumFile(long jarg1, toolkit jarg1_, String jarg2);
  public final static native void toolkit_getHumdrum__SWIG_0(long jarg1, toolkit jarg1_, long jarg2);
  public final static native String toolkit_getHumdrum__SWIG_1(long jarg1, toolkit jarg1_);
  public final static native String toolkit_getElementsAtTime(long jarg1, toolkit jarg1_, int jarg2);
  public final static native String toolkit_getMEI__SWIG_0(long jarg1, toolkit jarg1_, int jarg2, boolean jarg3);
  public final static native String toolkit_getMEI__SWIG_1(long jarg1, toolkit jarg1_, int jarg2);
  public final static native String toolkit_getMEI__SWIG_2(long jarg1, toolkit jarg1_);
  public final static native String toolkit_getElementAttr(long jarg1, toolkit jarg1_, String jarg2);
  public final static native void toolkit_redoLayout(long jarg1, toolkit jarg1_);
  public final static native void toolkit_redoPagePitchPosLayout(long jarg1, toolkit jarg1_);
  public final static native int toolkit_getPageWithElement(long jarg1, toolkit jarg1_, String jarg2);
  public final static native int toolkit_getTimeForElement(long jarg1, toolkit jarg1_, String jarg2);
  public final static native boolean toolkit_setScale(long jarg1, toolkit jarg1_, int jarg2);
  public final static native int toolkit_getScale(long jarg1, toolkit jarg1_);
  public final static native boolean toolkit_setFormat__SWIG_0(long jarg1, toolkit jarg1_, String jarg2);
  public final static native void toolkit_setFormat__SWIG_1(long jarg1, toolkit jarg1_, int jarg2);
  public final static native int toolkit_getFormat(long jarg1, toolkit jarg1_);
  public final static native boolean toolkit_setOutputFormat__SWIG_0(long jarg1, toolkit jarg1_, String jarg2);
  public final static native void toolkit_setOutputFormat__SWIG_1(long jarg1, toolkit jarg1_, int jarg2);
  public final static native int toolkit_getOutputFormat(long jarg1, toolkit jarg1_);
  public final static native int toolkit_identifyInputFormat(long jarg1, toolkit jarg1_, String jarg2);
  public final static native void toolkit_setScoreBasedMei(long jarg1, toolkit jarg1_, boolean jarg2);
  public final static native boolean toolkit_getScoreBasedMei(long jarg1, toolkit jarg1_);
  public final static native int toolkit_getPageCount(long jarg1, toolkit jarg1_);
  public final static native boolean toolkit_drag(long jarg1, toolkit jarg1_, String jarg2, int jarg3, int jarg4);
  public final static native boolean toolkit_insert(long jarg1, toolkit jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native boolean toolkit_set(long jarg1, toolkit jarg1_, String jarg2, String jarg3, String jarg4);
}
