<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.music_encoding</groupId>
		<artifactId>MEI-oXygen</artifactId>
		<version>1.0.0-develop</version>
	</parent>
	<artifactId>bundle-plugins</artifactId>
	<developers>
    <developer>
      <name>Alex Jitianu</name>
      <email>alex_jitianu@sync.ro</email>
      <roles>
        <role>manager</role>
      </roles>
    </developer>
    <developer>
      <name>Dan Caprioara</name>
      <email>dan@sync.ro</email>
      <roles>
        <role>co-manager</role>
      </roles>
    </developer>
  </developers>
  <dependencies>
		<!-- You can configure here all the plugins you want to use in an oXygen 
			installation. -->
		<!--<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>oxygen-sample-plugin-capitalize-lines</artifactId>
			<version>${project.version}</version>
			<type>jar</type>
			<classifier>plugin</classifier>
		</dependency>-->
		<!--<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>oxygen-sample-plugin-conversion</artifactId>
			<version>${project.version}</version>
			<type>jar</type>
			<classifier>plugin</classifier>
		</dependency>-->
		<!--<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>oxygen-sample-plugin-broken-links-checker</artifactId>
			<version>${project.version}</version>
			<type>jar</type>
			<classifier>plugin</classifier>
		</dependency>-->
		<!--<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>oxygen-sample-plugin-custom-open-redirect</artifactId>
			<version>${project.version}</version>
			<type>jar</type>
			<classifier>plugin</classifier>
		</dependency>-->
		<!--<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>oxygen-sample-plugin-custom-protocol</artifactId>
			<version>${project.version}</version>
			<type>jar</type>
			<classifier>plugin</classifier>
		</dependency>-->
		<!--<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>oxygen-sample-plugin-format-preserve-text</artifactId>
			<version>${project.version}</version>
			<type>jar</type>
			<classifier>plugin</classifier>
		</dependency>-->
		<!--<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>oxygen-sample-plugin-formsentences</artifactId>
			<version>${project.version}</version>
			<type>jar</type>
			<classifier>plugin</classifier>
		</dependency>-->
		<!--<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>oxygen-sample-plugin-formwords</artifactId>
			<version>${project.version}</version>
			<type>jar</type>
			<classifier>plugin</classifier>
		</dependency>-->
		<!--<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>oxygen-sample-plugin-impose-options</artifactId>
			<version>${project.version}</version>
			<type>jar</type>
			<classifier>plugin</classifier>
		</dependency>-->
		<!--<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>oxygen-sample-plugin-lowercase</artifactId>
			<version>${project.version}</version>
			<type>jar</type>
			<classifier>plugin</classifier>
		</dependency>-->
		<!--<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>oxygen-sample-plugin-components-validator</artifactId>
			<version>${project.version}</version>
			<type>jar</type>
			<classifier>plugin</classifier>
		</dependency>-->
		<!--<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>oxygen-sample-plugin-uppercase</artifactId>
			<version>${project.version}</version>
			<type>jar</type>
			<classifier>plugin</classifier>
		</dependency>-->
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>MEI-oXygen-plugin-workspace-access</artifactId>
			<version>${project.version}</version>
			<type>jar</type>
			<classifier>plugin</classifier>
		</dependency>
		<!--<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>oxygen-sample-plugin-zeroindent</artifactId>
			<version>${project.version}</version>
			<type>jar</type>
			<classifier>plugin</classifier>
		</dependency>-->
		<!--<dependency>
			<groupId>com.oxygenxml</groupId>
			<artifactId>web-author-mathml-plugin</artifactId>
			<version>${oxygen.sdk.version}</version>
			<type>jar</type>
			<classifier>plugin</classifier>
		</dependency>-->
    <!--<dependency>
       <groupId>com.oxygenxml</groupId>
       <artifactId>web-author-svg-plugin</artifactId>
       <version>${oxygen.sdk.version}</version>
       <type>jar</type>
       <classifier>plugin</classifier>
    </dependency>-->
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-dependency-plugin</artifactId>
				<groupId>org.apache.maven.plugins</groupId>
				<version>2.8</version>
				<executions>
					<execution>
						<id>extract-plugin-zip-artifacts</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>unpack-dependencies</goal>
						</goals>
						<configuration>
							<excludes>META-INF/**</excludes>
							<outputDirectory>${project.build.directory}/deps/</outputDirectory>
							<overWriteReleases>true</overWriteReleases>
							<overWriteSnapshots>true</overWriteSnapshots>
							<classifier>plugin</classifier>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-antrun-plugin</artifactId>
				<groupId>org.apache.maven.plugins</groupId>
				<version>1.7</version>
				<executions>
					<execution>
						<phase>prepare-package</phase>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<target>
								<copy file="${project.basedir}/plugin.dtd" toFile="${project.build.directory}/deps/plugin.dtd" force="true" />
								<zip destfile="${project.build.directory}/classes/plugins.zip">
									<zipfileset dir="${project.build.directory}/deps" includes="**/*" />
									<zipfileset dir="${project.basedir}/dropins" includes="**/*" />
								</zip>
							</target>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>

</project>
