# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Set env.version
      if: ${{ github.ref_name == 'develop' }}
      run: echo "version=`git describe --tags --alwaysb HEAD`" >> $GITHUB_ENV
    - name: Echo env.version
      run: echo ${{ env.version }} 
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: oXygen-MEI-addon-${{ env.version }}
        path: dist/*/
        retention-days: 5
